name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ## Sets environment variable
  GO_BOOKING_API_SECRET: ${{ secrets.GO_BOOKING_API_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # The "test" workflow
  test:

    name: Run Tests
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          #POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Setup Go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:

      # The Go version to download (if necessary) and use.
        go-version: 1.18
   
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Build
      run: go build -v ./...

    # Run testing on the code
    - name: Test
      run: go test -v ./...